"""Deterministic Agent permission evaluation."""

from nicekit.agent.permissions.actions import (
    CanonicalToolAction,
    ResolvedActionScope,
    ResolvedResource,
    ResourceResolutionError,
    ResourceResolver,
    canonical_action_payload,
    canonicalize_tool_action,
    register_material_arguments,
    register_resource_resolver,
    resolve_action_scope,
)
from nicekit.agent.permissions.approval import (
    ApprovalBundleUpdate,
    ApprovalDecisionError,
    apply_approval_decisions,
    is_approval_bundle,
    supersede_pending_approval_bundle,
)
from nicekit.agent.permissions.audit import (
    PermissionAuditAction,
    PermissionAuditDetail,
    add_permission_audit,
    permission_event_audit_detail,
)
from nicekit.agent.permissions.grants import (
    list_active_permission_grants,
    public_permission_grant,
    revoke_permission_grant,
)
from nicekit.agent.permissions.policy import (
    CapabilityBoundary,
    EffectivePermissionPolicy,
    PolicyEvaluation,
    ShadowPolicyComparison,
    evaluate_tool_action,
    evaluate_tool_action_with_shadow,
    load_effective_policy,
    policy_snapshot_payload,
)
from nicekit.agent.permissions.reviewer import (
    APPROVAL_REVIEW_SYSTEM_PROMPT,
    APPROVAL_REVIEW_TASK,
    DEFAULT_APPROVAL_REVIEW_SYSTEM_PROMPT,
    ApprovalReviewOutput,
    ApprovalReviewResult,
    ReviewerDecision,
    ReviewerOverrideError,
    ReviewerRiskFlag,
    active_reviewer_overrides,
    consume_reviewer_override,
    review_tool_action,
    serialize_reviewer_context,
    set_approval_review_system_prompt,
)

__all__ = [
    "CanonicalToolAction",
    "CapabilityBoundary",
    "DEFAULT_APPROVAL_REVIEW_SYSTEM_PROMPT",
    "ResolvedResource",
    "ResourceResolutionError",
    "ResourceResolver",
    "register_material_arguments",
    "register_resource_resolver",
    "resolve_action_scope",
    "set_approval_review_system_prompt",
    "ApprovalBundleUpdate",
    "ApprovalDecisionError",
    "ApprovalReviewOutput",
    "ApprovalReviewResult",
    "APPROVAL_REVIEW_SYSTEM_PROMPT",
    "APPROVAL_REVIEW_TASK",
    "EffectivePermissionPolicy",
    "PermissionAuditAction",
    "PermissionAuditDetail",
    "PolicyEvaluation",
    "ShadowPolicyComparison",
    "ResolvedActionScope",
    "ReviewerDecision",
    "ReviewerOverrideError",
    "ReviewerRiskFlag",
    "active_reviewer_overrides",
    "add_permission_audit",
    "canonical_action_payload",
    "canonicalize_tool_action",
    "consume_reviewer_override",
    "apply_approval_decisions",
    "evaluate_tool_action",
    "evaluate_tool_action_with_shadow",
    "load_effective_policy",
    "policy_snapshot_payload",
    "permission_event_audit_detail",
    "is_approval_bundle",
    "list_active_permission_grants",
    "public_permission_grant",
    "revoke_permission_grant",
    "review_tool_action",
    "serialize_reviewer_context",
    "supersede_pending_approval_bundle",
]
